### ISSUE TITLE
`w3 space info` should show the name of the space

### ISSUE THREAD

**Issue by olizilla** [w3s-project/w3cli#162]
`w3 space ls` shows me the did and the **nickname** of all the spaces the agent knows about.

```shell
$ w3 space ls
* did:key:z6MkhuXLUzZrrQeWMe3CrPNHsH6pwHjaYFjh2ZipjZbzxcmR add-to-web3
```

`w3 space info` shows the did and the provider, but not the nickname. It feels like `info` should show everything we know about that space and at least the nickname where we have it.

```shell
$ w3 space info

      DID: did:key:z6MkhuXLUzZrrQeWMe3CrPNHsH6pwHjaYFjh2ZipjZbzxcmR
Providers: did:web:web3.storage
```

**Comment by alanshaw** [comment]
resolved by https://github.com/w3s-project/w3cli/pull/164
